-- Recria a tabela de atualizações de localização
CREATE TABLE IF NOT EXISTS public.location_updates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    lat double precision NOT NULL,
    lng double precision NOT NULL,
    accuracy double precision,
    speed double precision,
    heading double precision
);

-- Habilita o Realtime para a tabela
ALTER PUBLICATION supabase_realtime ADD TABLE public.location_updates;

-- Habilita Row Level Security (RLS)
ALTER TABLE public.location_updates ENABLE ROW LEVEL SECURITY;

-- Cria políticas de segurança (permitir leitura e escrita pública para este app de demonstração)
-- OBS: Em produção, você pode querer restringir o INSERT apenas para usuários autenticados
CREATE POLICY "Enable read access for all users" 
ON public.location_updates 
FOR SELECT 
USING (true);

CREATE POLICY "Enable insert access for all users" 
ON public.location_updates 
FOR INSERT 
WITH CHECK (true);

-- Opcional: Recriar tabela de câmeras se necessário
CREATE TABLE IF NOT EXISTS public.cameras (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text,
    lat double precision,
    lng double precision,
    youtube_link text,
    coverage_area jsonb
);

ALTER TABLE public.cameras ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" 
ON public.cameras 
FOR SELECT 
USING (true);
